### ISSUE TITLE
Custom ID in add method

### ISSUE THREAD

**Issue by sedestrian** [geofirestore/geofirestore-js#93]
Hi, reading the documentation it looks like the only way to add a document to a collection with a custom "coordinates" key is the GeoCollectionReference.add() method, but in my application i need to set a custom document id, and the add() method doesn't provide the option of a custom id. Now if i use a GeoDocumentReference and use the set() method i lose the ability to set a custom "coordinates" key. It would be pretty useful to add an option to set a custom id in the add() method :)

**Comment by sedestrian** [comment]
Also, if i try to create the document with the set method and no custom "coordinates" key, i get this error

`Unhandled error Error: Invalid GeoFirestore document: no valid key exists
    at findCoordinatesKey (/user_code/node_modules/geofirestore/dist/index.cjs.js:308:15)
    at encodeSetDocument (/user_code/node_modules/geofirestore/dist/index.cjs.js:242:27)
    at GeoDocumentReference.set (/user_code/node_modules/geofirestore/dist/index.cjs.js:970:35)
    at Promise (/user_code/lib/index.js:98:17)
    at Object.<anonymous> (/user_code/lib/index.js:97:16)
    at next (native)
    at /user_code/lib/index.js:7:71
    at __awaiter (/user_code/lib/index.js:3:12)
    at exports.create_user.functions.https.onCall (/user_code/lib/index.js:87:65)
    at /user_code/node_modules/firebase-functions/lib/providers/https.js:330:32`

**Comment by MichaelSolati** [comment]
The set document method has a second argument of a `setOptions` where you can declare your custom key => https://geofirestore.com/interfaces/_geofirestoretypes_.geofirestoretypes.setoptions.html
